# vi: sw=2 ts=2 sts=2 expandtab

name: Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy_version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install caproto
      shell: bash -l {0}
      run: |
        source .ci/install.sh doc test

    - name: Install system dependencies
      run: sudo apt-get install -y graphviz

    - name: Check version tag for deployment
      id: version
      shell: bash -l {0}
      run: |
        if [[ $GITHUB_EVENT_NAME == "pull_request" || $GITHUB_EVENT_NAME == "push" ]]; then
          echo "Version is: master"
          echo "::set-output name=version::master"
        else
          echo "Version is: $(git describe --tags)"
          echo "::set-output name=version::$(git describe --tags)"
        fi

    - name: Build Docs
      shell: bash -l {0}
      env:
        EPICS_CAS_AUTO_BEACON_ADDR_LIST: "YES"
        EPICS_CAS_BEACON_ADDR_LIST: ""
        EPICS_CAS_INTF_ADDR_LIST: ""
        EPICS_CA_ADDR_LIST: "10.1.255.255"
        EPICS_CA_AUTO_ADDR_LIST: "NO"

      run: |
        caproto-repeater -v &
        cd doc
        set -e
        make html

    - uses: actions/upload-artifact@v2
      with:
        name: built-docs
        path: doc/build/html

  deploy:
    if: github.repository_owner == 'caproto'
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - uses: actions/download-artifact@v2
      with:
        name: built-docs
        path: doc/build/html

    - uses: actions/checkout@v2
      with:
        repository: "caproto/caproto.github.io"
        ref: "master"
        path: "caproto.github.io"

    - name: Install deployment dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install doctr-versions-menu

    - name: Ready deployment
      env:
        version: ${{needs.build.outputs.deploy_version}}
      run: |
        echo "To deploy version: ${version}"
        set -x
        pushd caproto.github.io/caproto
        rm -rf "./${version}"
        cp -R "$GITHUB_WORKSPACE/doc/build/html" "${version}"
        doctr-versions-menu \
          --debug \
          --outfile versions.json \
          --write-index-html \
          --write-versions-py \
          --no-downloads-file
        popd

    - name: Deploy documentation to caproto.github.io.
      # Pin to the SHA and not the tag for security reasons:
      if: ${{ github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501  # v3.7.3
      with:
        deploy_key: ${{ secrets.ACTIONS_DOCUMENTATION_DEPLOY_KEY }}
        publish_branch: master
        publish_dir: caproto.github.io/caproto
        external_repository: caproto/caproto.github.io
        destination_dir: caproto
        keep_files: false  # Remove old files if regenerating docs
        force_orphan: false  # Keep git history.
